### ISSUE TITLE
感谢您的项目，提一个小小的建议

### ISSUE THREAD

**Issue by jr-h** [ma6254/FictionDown#10]
q(≧▽≦q)感谢您的项目，解决了在下的痛。
但是提个小建议：能否在发布`release`时给文件签名呢？
(目的:
1. 防止您的权益受到侵害，毕竟国内有很多无良，从github上盗窃项目，套层壳然后收费售卖......
2. 不知道您有没有用过`kms pico`呢？作者发布在一个国外的论坛上（被墙了），然后很多人建立仿站在文件里藏上挖矿⛏病毒......希望您能签名......最好给一个`MD5`码哦~)
最后的最后，再次感谢orz!

**Comment by ma6254** [comment]
下个版本发布时会加上哈希信息
二次打包没有什么好办法，我是在输出文档和运行信息中加入了这个项目的源地址

**Comment by ma6254** [comment]
已通过Github Action完成自动Release，CheckSum算法为sha256
