### ISSUE TITLE
cmd批处理文件中执行时出现乱码

### ISSUE THREAD

**Issue by Jonathon52306** [ma6254/FictionDown#13]
执行环境：
![image](https://user-images.githubusercontent.com/46887506/74705177-f2f01080-524d-11ea-834e-321e6f4d4ab5.png)
cmd属性：
![image](https://user-images.githubusercontent.com/46887506/74705309-6134d300-524e-11ea-8aed-7009f0b37c5e.png)
脚本：
`@echo off

SET bookname=%1

SET writer=%2

SET url=%3

cd C:\Coding\workspace\FictionDown\FictionDown_cache

@echo on

FictionDown -u %url% --driver chromedp d -t 32

FictionDown -i %bookname%-%writer%-起点中文网.FictionDown s -k %bookname% -p

FictionDown -i %bookname%-%writer%-起点中文网.FictionDown d -t 32

FictionDown -i %bookname%-%writer%-起点中文网.FictionDown conv txt -o 

C:\Coding\workspace\FictionDown\FictionDown_downloads`

执行界面：
![image](https://user-images.githubusercontent.com/46887506/74705461-eddf9100-524e-11ea-9d00-3bd2db1c598c.png)
输入命令为：FictionDown.bat 重生创业时代 公子不歌 https://book.qidian.com/info/1016320879
用法：FictionDown.bat space（书名）space（作者）space（起点链接）[space为空格]

**Comment by ma6254** [comment]
你的脚本文件的编码格式是什么？UTF8还是GBK？

**Comment by Jonathon52306** [comment]
UTF8

**Comment by Jonathon52306** [comment]
换编码之后好了

**Comment by Jonathon52306** [comment]
谢谢
