### ISSUE TITLE
无法下载,起点

### ISSUE THREAD

**Issue by Mr-oy** [ma6254/FictionDown#19]
您好,我是第一次用这个FictionDown,我想用它下载"诡秘之主",带到kindle上二刷.

由于没有用过go语言相关程序,我又害怕出错,所有我的安装方式为:
1.打开了v2rayNG翻墙
2.下载安装了go语言支持(.msi for amd64)
3.go env -w GO111MODULE=on
4.go env -w GOPROXY=https://goproxy.cn,direct
5.go get -v github.com/ma6254/FictionDown@latest

似乎是安装成功了
![image](https://user-images.githubusercontent.com/69334528/104094149-09002880-5287-11eb-8ae6-48802088ea7b.png)

然而接下来无论是我尝试搜索
![image](https://user-images.githubusercontent.com/69334528/104094242-78761800-5287-11eb-9a97-0b1f9ade9e64.png)

还是我尝试提供网站直接下载
![image](https://user-images.githubusercontent.com/69334528/104094274-c3902b00-5287-11eb-8e38-643c8e363c10.png)

似乎运行并不正常,是我没安装好吗?

平台:
win10  企业版 LTSC 1809(os内部版本 17763.1637)
go version go1.15.6 windows/amd64

2021.1.9

**Comment by ma6254** [comment]
```
# 有时会发生`not match volumes`的错误，请启用Chromedp或者PhantomJS
# Use Chromedp
> ./FictionDown --url https://book.qidian.com/info/3249362 --driver chromedp d
# Use PhantomJS
> ./FictionDown --url https://book.qidian.com/info/3249362 --driver phantomjs d
```

**Comment by Mr-oy** [comment]
谢您,这个我从*readme.md*里看到了,那个运行时错误是怎么回事呢
![image](https://user-images.githubusercontent.com/69334528/104116118-aaca5880-530d-11eb-833d-7f198301d280.png)
