### ISSUE TITLE
[Bugs] 当章节内容不存在时，会出现 Error: No matching content

### ISSUE THREAD

**Issue by edmund-zhao** [ma6254/FictionDown#21]
[‘章节链接’](https://www.81new.net/168/168136/59590997.html)
![image](https://user-images.githubusercontent.com/53864204/115141863-28baa000-a071-11eb-8b7c-9a99cee6bbcf.png)
- 程序会一直重放请求，无法跳过
- 已启用Chromedb

**Comment by ma6254** [comment]
可以手动编辑FictionDownCache文件，将章节内容设置为非空以跳过该章节

**Comment by edmund-zhao** [comment]
> 可以手动编辑FictionDownCache文件，将章节内容设置为非空以跳过该章节

好的，我暂时的解决方案时设定shell、cmd运行的最长时间，如果超过最长时间900s，就自动kill进程

**Comment by edmund-zhao** [comment]
> 可以手动编辑FictionDownCache文件，将章节内容设置为非空以跳过该章节

当批量爬取时，这种编辑方法不能很好的解决问题

**Comment by ma6254** [comment]
稍后更新单章爬取重试次数限制

**Comment by edmund-zhao** [comment]
> 稍后更新单章爬取重试次数限制

好的，麻烦作者您了
