### ISSUE TITLE
无法读取起点章节，内容为空

### ISSUE THREAD

**Issue by Donge-ying** [ma6254/FictionDown#28]
bookurl: https://book.qidian.com/info/1025813823/
bookname: 仙朝纪元
author: 西城冷月
coverurl: https://bookcover.yuewen.com/qdbimg/349573/1025813823/180
description: |-
  旧世之末，余火回光！
  龙蛇起陆的仙道盛景、缱绻多情的绝代佳人，春色绚烂下，是那腐朽的灰败。
  仙人在沉沦中徘徊，旧神在欲望中复苏……
  建仙朝、铸仙鼎，口含天宪，言出法随，叫那天地换个新纪元！
  这是一个幽幽长夜之内，一点星火乍起，煦照九天十地，三界六道……的故事。
tmap: []
volumes:
- name: 作品相关
  isvip: false
  chapters: []
- name: 潜龙勿用
  isvip: false
  chapters: []
- name: 潜龙勿用
  isvip: true
  chapters: []
- name: 见龙在田
  isvip: true
  chapters: []
- name: 终日乾乾
  isvip: true
  chapters: []

**Comment by donmor** [comment]
貌似是加密，我用的脚本也寄了

**Comment by ma6254** [comment]
寄啦
